FROM python:3.12.10

RUN apt-get update && apt-get install -y postgresql-client

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
RUN chmod 755 .

COPY docker/wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

ENV PYTHONUNBUFFERED=1

CMD ["/wait-for-it.sh", "postgres:5432", "--", "gunicorn", "core.project.wsgi:application", "--bind", "0.0.0.0:8000"]