version: '3.9'

services:
  django:
    build:
      context: ..
      dockerfile: docker/Dockerfile.django
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ../.env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 200M

  migrate:
    build:
      context: ..
      dockerfile: docker/Dockerfile.django
    volumes:
      - ..:/app
    env_file:
      - ../.env
    depends_on:
      - postgres
    command: /bin/bash -c "while ! pg_isready -h postgres -p 5432; do sleep 2; done; python manage.py migrate"
    deploy:
      resources:
        limits:
          memory: 150M

  postgres:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ../.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "35432:5432"
    deploy:
      resources:
        limits:
          memory: 150M
    command: postgres -c shared_buffers=64MB -c effective_cache_size=128MB

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 50M
    command: redis-server --maxmemory 32mb --maxmemory-policy allkeys-lru

  celery:
    build:
      context: ..
      dockerfile: docker/Dockerfile.django
    command: >
      sh -c "/wait-for-it.sh redis:6379 --  && celery -A core.project worker --loglevel=info --concurrency=1 --max-tasks-per-child=50"
    env_file:
      - ../.env
    depends_on:
      - redis
      - postgres
    volumes:
      - ..:/app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 100M

  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile.bot
    env_file:
      - ../.env
    depends_on:
      - django
      - redis
    restart: unless-stopped
    working_dir: /app/bot
    command: sh -c "while true; do python -u bot.py; sleep 10; done"
    deploy:
      resources:
        limits:
          memory: 200M

volumes:
  pgdata: