# Generated by Django 5.2.7 on 2025-10-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Напоминание отправлено'),
        ),
    ]
